name: 🚧 Integration
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 7
          run_install: true
      - run: pnpm test
